[env]
TERM = "xterm-256color"

working_directory = "C:/" #Change this to your user name or the directory you want to start in

[shell]
program = "C:/Program Files/WindowsApps/Microsoft.PowerShellPreview_7.5.3.0_x64__8wekyb3d8bbwe/pwsh.exe -nologo -noexit" # Change this to your shell path (I use powershell preview)

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 13

[window]
decorations = "Full"
opacity = 0.75
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = false
blur = true #Only works on linux/MacOS
dimensions = { columns = 125, lines = 35 } #Configure the size of the window i like this size for my workflow this isn't pixels, it's columns and lines
position = { x = 700, y = 400 } #Configure the position of the window considerating your screen resolution and window size (here is for pixels)

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[keyboard]
bindings = [
{ key = "N", 		mods = "Control|Shift",		action = "CreateNewWindow" },
{ key = "Enter", 	mods = "Alt", 			action = "ToggleFullscreen"},
{ key = "Q", 		mods = "Control|Shift", 	action = "Quit"},
{ key = "Backspace", 	mods = "Alt", 			action = "Minimize"},
{ key = "Up", 		mods = "Alt", 			action = "IncreaseFontSize"},
{ key = "Down", 	mods = "Alt", 			action = "DecreaseFontSize"},
{ key = "Right", 	mods = "Alt", 			action = "ResetFontSize"},
{ key = "S", 		mods = "Control|Shift", 	action = "ScrollToBottom"},
{ key = "W", 		mods = "Control|Shift", 	action = "ScrollToTop"},
]

